[package]
name = "raytracer"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
console = "0.15.11"
indicatif = "0.17.11"
rand = "0.9.1"
palette = "0.7.6"

[profile.dev]
opt-level = 1

[profile.profiling]
inherits = "release"
debug = true